### ISSUE TITLE
Add AutoHide Macro to FreeCAD Preferences Dialog

### ISSUE THREAD

**Issue by dcapeletti** [HakanSeven12/FreeCAD-AutoHide-Docks#2]
Hello, just as the Remember workbench macro has been a [separate macro](https://forum.freecadweb.org/viewtopic.php?f=3&t=43326) and has now been [merged with the main branch of freecad](https://github.com/FreeCAD/FreeCAD/pull/3072), I think the same should happen with this macro once it is well tested and documented, merging it with the main branch of FreeCAD.

Greetings

**Comment by HakanSeven12** [comment]
Look at this: https://forum.freecadweb.org/viewtopic.php?f=34&t=44937
